import { randomUUID, createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import type { Job, ToolStatus } from '../types/index.js';
import { AuditLogger } from '../core/AuditLogger.js';
import { QuotaStore } from '../core/QuotaStore.js';
import { TrustVerifierPaymentAgent } from '../agents/TrustVerifierPaymentAgent.js';
import { RedTeamRepoScannerAgent } from '../agents/RedTeamRepoScannerAgent.js';
import { BlueTeamHardeningReportAgent } from '../agents/BlueTeamHardeningReportAgent.js';
import { ExternalSecurityToolRunner } from '../tools/ExternalSecurityToolRunner.js';
import { ReportGenerator } from '../report/ReportGenerator.js';
export class MainOrchestrator { jobs = new Map<string, Job>(); quota = new QuotaStore(); audit = new AuditLogger(); trust = new TrustVerifierPaymentAgent(); red = new RedTeamRepoScannerAgent(); blue = new BlueTeamHardeningReportAgent();
  hashUser(userId:string){ return createHash('sha256').update(userId).digest('hex').slice(0,16); }
  async createScan(userId:string, targetUrl:string): Promise<Job> { const job:Job={id:`JOB-${randomUUID().slice(0,8)}`,userIdHash:this.hashUser(userId),targetUrl,verified:false,scopeLocked:false,scopeHost:'',state:'RECEIVE_REQUEST',freeScanUsed:false,credits:0,findings:[]}; this.jobs.set(job.id,job); await this.audit.transition(job.id,job.userIdHash,'MainOrchestrator','START','RECEIVE_REQUEST','create_job','telegram','DONE',{targetUrl},{job_id:job.id}); return job; }
  async demo(): Promise<{job:Job; reports:{json:string;pdf:string}; transcript:string; tools:ToolStatus[]}> { const job=await this.createScan('demo-user','https://demo-owned-site.local'); const challenge=this.trust.challenge(job); await this.audit.transition(job.id,job.userIdHash,'TrustVerifierPaymentAgent','PRE_ENGAGEMENT_CHECK','GENERATE_OWNERSHIP_CHALLENGE','challenge','ScopeGuard','DONE',{}, {decision:challenge.decision}); const verify=this.trust.verifyDemo(job,`clawvapt-verify-${job.id}`); await this.audit.transition(job.id,job.userIdHash,'TrustVerifierPaymentAgent','VERIFY_OWNERSHIP','LOCK_SCOPE','verify_demo','ScopeGuard',verify.status,{}, {scope:job.scopeHost}); const q=this.quota.check(job.userIdHash); if(q.allowed){ this.quota.consume(job.userIdHash); await this.audit.transition(job.id,job.userIdHash,'TrustVerifierPaymentAgent','LOCK_SCOPE','CHECK_QUOTA_OR_PAYMENT','first_scan_free','QuotaStore','DONE',{},q); }
    const second=this.quota.check(job.userIdHash); if(!second.allowed){ const payment=await this.trust.createPayment(job); await this.audit.transition(job.id,job.userIdHash,'TrustVerifierPaymentAgent','CHECK_QUOTA_OR_PAYMENT','CHECK_QUOTA_OR_PAYMENT','payment_gate','PakasirAdapter',payment.status,{}, {orderId:job.orderId}); this.quota.addCredits(job.userIdHash,10); await this.audit.transition(job.id,job.userIdHash,'TrustVerifierPaymentAgent','CHECK_QUOTA_OR_PAYMENT','CREATE_SCAN_PLAN','simulate_payment','PakasirAdapter','MOCK',{orderId:job.orderId},{credits_added:10}); }
    const scan=await this.red.scan(job); await this.audit.transition(job.id,job.userIdHash,'RedTeamRepoScannerAgent','CREATE_SCAN_PLAN','SCORE_AND_PRIORITIZE','safe_scan','BuiltInScanners','DONE',{}, {findings:scan.findings.length}); const patch=await this.blue.patch(job); const plan=this.blue.plan(job); await this.audit.transition(job.id,job.userIdHash,'BlueTeamHardeningReportAgent','OFFER_REMEDIATION','APPROVAL_GATE','plan_patch','PatchGenerator','MOCK',{}, {patch}); await this.audit.transition(job.id,job.userIdHash,'BlueTeamHardeningReportAgent','APPROVAL_GATE','RETEST','retest_required','RetestRunner','DONE',{}, {fixed_marked:false}); const tools=await new ExternalSecurityToolRunner(this.audit).checkAll(job.id,job.userIdHash); const reports=await new ReportGenerator().generate(job,scan.correlations,tools,true); await this.audit.transition(job.id,job.userIdHash,'BlueTeamHardeningReportAgent','GENERATE_FINAL_REPORT','SEND_TELEGRAM_SUMMARY','report','ReportGenerator','DONE',{}, reports); const transcript=await this.writeTranscript(job,reports); return {job,reports,transcript,tools}; }
  async writeTranscript(job:Job,reports:{json:string;pdf:string}){ await mkdir('docs',{recursive:true}); const path='docs/demo-transcript.md'; await writeFile(path,`# ClawVAPT Demo Transcript\n\n/start\n/help\n/demo\n/scan ${job.targetUrl}\n/verify ${job.id}\n/status ${job.id}\n/report ${job.id}\n/harden ${job.id}\n/pay\n/check_payment ${job.orderId}\n/simulate_payment ${job.orderId}\n\nReports: ${reports.json}, ${reports.pdf}\nSafety: ownership verified, scope locked, secrets redacted.\n`); return path; }
}
