import { mkdir, writeFile } from 'node:fs/promises';
import type { Finding, Job, ToolStatus } from '../types/index.js';
import type { Correlation } from '../tools/Correlator.js';
function escPdf(s:string){ return s.replace(/[\\()]/g, m=>`\\${m}`).replace(/[\r\n]+/g,' '); }
export class ReportGenerator {
  constructor(private dir = process.env.REPORT_DIR || 'reports') {}
  async generate(job: Job, correlations: Correlation[], tools: ToolStatus[], sample=false): Promise<{json:string; pdf:string}> { await mkdir(this.dir,{recursive:true}); const base = sample ? 'sample_report' : `${job.id}_report`; const jsonPath=`${this.dir}/${base}.json`; const pdfPath=`${this.dir}/${base}.pdf`; const report = { job_id: job.id, generated_at: new Date().toISOString(), authorization_and_scope:{ verified:job.verified, scope_locked:job.scopeLocked, scope_host:job.scopeHost }, methodology:['pre-engagement','ownership verification','scope lock','safe URL scanner','safe repo scanner','normalization','correlation','redaction','reporting'], tools_used:[{name:'SafeUrlScanner',mode:'BUILTIN',status:'DONE'},{name:'RepoScanner',mode:'BUILTIN',status:'DONE'},...tools], findings: job.findings, correlations, limitations:['Demo uses safe deterministic target for .local domains.','External adapters are availability-checked and not executed unless installed and scope gates pass.','Payment may be MOCK in DEMO_MODE.'], redaction_applied:true };
    await writeFile(jsonPath, JSON.stringify(report,null,2)); await writeFile(pdfPath, this.pdf(report.findings)); return {json:jsonPath,pdf:pdfPath}; }
  private pdf(findings: Finding[]): string { const lines = ['ClawVAPT Sample Report','Executive Summary','Authorization and Scope','Methodology','Tools Used','Findings Summary',...findings.slice(0,12).map(f=>`${f.severity}: ${f.title}`),'Runtime-to-Code Correlation','Remediation Plan','Retest Results: no finding marked FIXED without retest','Hardening Recommendations','Compliance Guardrails','Limitations','Audit Trail Summary']; const body=lines.map((l,i)=>`BT /F1 12 Tf 50 ${760-i*22} Td (${escPdf(l)}) Tj ET`).join('\n'); const pdf=`%PDF-1.4\n1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj\n4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n5 0 obj << /Length ${body.length} >> stream\n${body}\nendstream endobj\nxref\n0 6\n0000000000 65535 f \ntrailer << /Root 1 0 R /Size 6 >>\nstartxref\n0\n%%EOF\n`; return pdf; }
}
