export interface PakasirTransaction { orderId: string; amount: number; paymentUrl: string; status: 'PENDING'|'PAID'|'MOCK_PAYMENT_CONFIRMED'; mode: 'sandbox'|'live'|'mock'; }
export class PakasirAdapter {
  baseUrl = process.env.PAKASIR_BASE_URL || 'https://app.pakasir.com'; slug = process.env.PAKASIR_SLUG || 'demo-clawvapt'; mode = process.env.PAKASIR_MODE || 'sandbox'; method = process.env.PAKASIR_DEFAULT_METHOD || 'qris';
  createPaymentUrl(orderId: string, amount = 25000): string { const qris = this.method === 'qris' ? '&qris_only=1' : ''; return `${this.baseUrl}/pay/${encodeURIComponent(this.slug)}/${amount}?order_id=${encodeURIComponent(orderId)}${qris}`; }
  async createTransaction(method: string, orderId: string, amount: number): Promise<PakasirTransaction> { if (!process.env.PAKASIR_API_KEY || process.env.DEMO_MODE === 'true') return { orderId, amount, paymentUrl: this.createPaymentUrl(orderId, amount), status: 'PENDING', mode: 'mock' }; return { orderId, amount, paymentUrl: this.createPaymentUrl(orderId, amount), status: 'PENDING', mode: this.mode === 'live' ? 'live' : 'sandbox' }; }
  async simulatePayment(orderId: string, amount: number): Promise<PakasirTransaction> { if (process.env.PAKASIR_MODE !== 'sandbox' && process.env.DEMO_MODE !== 'true') throw new Error('SIMULATION_DISABLED'); return { orderId, amount, paymentUrl: this.createPaymentUrl(orderId, amount), status: 'MOCK_PAYMENT_CONFIRMED', mode: 'mock' }; }
  async getTransactionDetail(orderId: string, amount: number): Promise<PakasirTransaction> { if (!process.env.PAKASIR_API_KEY || process.env.DEMO_MODE === 'true') return { orderId, amount, paymentUrl: this.createPaymentUrl(orderId, amount), status: 'MOCK_PAYMENT_CONFIRMED', mode: 'mock' }; return { orderId, amount, paymentUrl: this.createPaymentUrl(orderId, amount), status: 'PENDING', mode: this.mode === 'live' ? 'live' : 'sandbox' }; }
  async handleWebhook(payload: unknown): Promise<{status:'MOCK'|'INCOMPLETE'; accepted:boolean; note:string}> { void payload; return { status: 'INCOMPLETE', accepted: false, note: 'Webhook endpoint skeleton only; transaction detail validation required before credits.' }; }
}
